server:
  port: 8081

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://81.69.193.138:3306/my?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: jcahsy1314
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jc.springcloud.entities